apiVersion: v1
kind: Service
metadata:
  name: minibit-service
  namespace: minibit
  labels:
    app: minibit
spec:
  type: ClusterIP
  ports:
  - port: 25566
    targetPort: 25566
    protocol: TCP
    name: lobby
  - port: 25567
    targetPort: 25567
    protocol: TCP
    name: parkour
  - port: 25568
    targetPort: 25568
    protocol: TCP
    name: sumo
  - port: 25569
    targetPort: 25569
    protocol: TCP
    name: spaceshooter
  - port: 25570
    targetPort: 25570
    protocol: TCP
    name: classic
  - port: 25571
    targetPort: 25571
    protocol: TCP
    name: trainchase
  - port: 25572
    targetPort: 25572
    protocol: TCP
    name: bedwars
  - port: 25573
    targetPort: 25573
    protocol: TCP
    name: bridge
  - port: 25574
    targetPort: 25574
    protocol: TCP
    name: bowfight
  - port: 25575
    targetPort: 25575
    protocol: TCP
    name: boxing
  selector:
    app: minibit
