apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minibit-config-pvc
  namespace: minibit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Uncomment and specify your storage class if needed
  # storageClassName: standard
