apiVersion: v1
kind: Secret
metadata:
  name: minibit-secret
  namespace: minibit
type: Opaque
stringData:
  # Replace this with a secure random string before deploying
  # You can generate one with: openssl rand -base64 12
  FORWARDING_SECRET: "CHANGE_ME_PLEASE"
  VELOCITY_FORWARDING_SECRET: "CHANGE_ME_PLEASE"
